version: '3.8'
services:
  bff-web:
    build: 
      context: .
      dockerfile: bff-web/Dockerfile
    ports:
      - "8443:8443"

  bff-mobile:
    build: 
      context: .
      dockerfile: bff-mobile/Dockerfile
    ports:
      - "8444:8444"

  bff-atm:
    build: 
      context: .
      dockerfile: bff-atm/Dockerfile
    ports:
      - "8445:8445"
